#!/bin/bash

help () {
    cat << EOF
Script for setting resin shell environment
resin-vars [options]

Options:
    -h, --help
        Display this help and exit.

    -c, --config-path CONFIG_PATH
        Use a non default config.json file.
        Default: /mnt/boot/config.json
EOF
}

# Parse arguments
while [ "$#" -gt "0" ]; do
    key=$1
    case $key in
        -h|--help)
            help
            exit 0
            ;;
        -c|--config-path)
            CONFIG_PATH=$2
            shift
            ;;
        *)
            echo "[WARNING] $0 : Argument '$1' unknown. Ignoring."
            ;;
    esac
    shift
done

# Resin-boot mountpoint
BOOT_MOUNTPOINT="/mnt/boot"

# Default values
if [ -z "$CONFIG_PATH" ]; then
    CONFIG_PATH=$BOOT_MOUNTPOINT/config.json
fi

# If config.json provides redefinitions for our vars let us rewrite their
# runtime value
if [ -f $CONFIG_PATH ]; then
    eval "$(jq -r '@sh "
         REGISTRY_ENDPOINT=\(.registryEndpoint // "")
         CONFIG_HOSTNAME=\(.hostname // "hlnew-mc")
         PERSISTENT_LOGGING=\(.persistentLogging // "")
         COUNTRY=\(.country // "")
         UUID=\(.uuid // "")
         DEVICE_API_KEY=\(.deviceApiKey // "")
         DEVICE_TYPE=\(.deviceType // "")
         REGISTERED_AT=\(.registered_at // "")
         NTP_SERVERS=\(.ntpServers // "")
         DNS_SERVERS=\(.dnsServers // "")
         RSM_SSH_HOST=\(.rsmHost // "rsm.helioslite.net")
         RSM_SSH_PORT=\(.rsmPort // "5575")
         SSH_AUTHORIZED_KEYS=\(.authorizedKeys // "")
         PRIVATE_REGISTRY=\(.registry // "")
         PRIVATE_REGISTRY_PASSWORD=\(.registryPassword // "")
         "' $CONFIG_PATH)"
    if [ -z "$PERSISTENT_LOGGING" ]; then
        PERSISTENT_LOGGING=false
    fi
else
    echo "[WARNING] $0 : '$CONFIG_PATH' not found."
fi
