#!/bin/bash

set -e

source /usr/sbin/resin-vars
SSH_AUTHORIZED_KEYS=$(jq --raw-output '.sshAuthorizedKeys // empty' $CONFIG_PATH)

if [ ! -z "$SSH_AUTHORIZED_KEYS" ]; then
    echo "$SSH_AUTHORIZED_KEYS" | jq --raw-output '.[]' > /home/root/.ssh/authorized_keys
    chmod 0600 /home/root/.ssh/authorized_keys
fi
