#!/bin/bash
set -e

# shellcheck disable=SC1091
source /usr/sbin/resin-vars

# shellcheck disable=SC1091
source /etc/os-release

#
# MAIN
#
while read -r cmd
do
    IFS=" " read -r -a parse <<< "$cmd"

    if [ "${parse[0]}" == "info" ]; then
        HOSTNAME="$(hostname)"
        UNAME="$(uname -a)"
        FEATURES="[\"shutdown\", \"reboot\", \"update\"]"

        echo "{\
            \"id\": \"$ID\",\
            \"name\": \"$NAME\",\
            \"version\": \"$VERSION\",\
            \"version_id\": \"$VERSION_ID\",\
            \"pretty_name\": \"$PRETTY_NAME\",\
            \"resin_board_rev\": \"$RESIN_BOARD_REV\",\
            \"slug\": \"$SLUG\",\
            \"machine\": \"$MACHINE\",\
            \"variant\": \"$VARIANT\",\
            \"variant_id\": \"$VARIANT_ID\",\
            \"hostname\": \"$HOSTNAME\",\
            \"features\": $FEATURES,\
            \"uname\": \"$UNAME\"\
        }"
        continue
    fi
    if [ "${parse[0]}" == "reboot" ]; then
        systemctl reboot && echo "OK" || echo "ERROR"
        continue
    fi
    if [ "${parse[0]}" == "shutdown" ]; then
        systemctl poweroff && echo "OK" || echo "ERROR"
        continue
    fi
    if [ "${parse[0]}" == "update" ]; then
        if [ ! -z "${parse[1]}" ]; then
            echo "Hostapp-update not implemented yet..."
            #nohup run-resinhup.sh --force --hostos-version "${parse[1]}" > /dev/null 2>&1 &
        else
            echo "ERROR"
            continue
        fi

        sleep 4 && echo "OK"
        continue
    fi

    echo "WRONG"
done
